--INVENTORY & WAREHOUSE MANAGEMENT SYSTEM

--SECTION 1: CREATE DATABASE

CREATE DATABASE INVENTORY_WAREHOUSE_DB;

--SECTION 2: OLTP SCHEMA - CREATE TABLES

-- 2.1 SUPPLIERS -------------------------------------------------------------
CREATE TABLE SUPPLIERS (
SUPPLIER_ID SERIAL PRIMARY KEY,
SUPPLIER_NAME VARCHAR(150) NOT NULL,
CONTACT_NAME VARCHAR(100),
PHONE VARCHAR(20)  UNIQUE,
EMAIL VARCHAR(120) UNIQUE,
ADDRESS VARCHAR(255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2.2 WAREHOUSES --------------------------------------------------------
CREATE TABLE WAREHOUSES (
WAREHOUSE_ID SERIAL PRIMARY KEY,
WAREHOUSE_NAME VARCHAR(100) NOT NULL UNIQUE,
LOCATION VARCHAR(150) NOT NULL,
CAPACITY INT CHECK (CAPACITY > 0),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2.3 PRODUCTS ------------------------------------------------------------
CREATE TABLE PRODUCTS (
PRODUCT_ID SERIAL PRIMARY KEY,
PRODUCT_NAME VARCHAR(150) NOT NULL,
CATEGORY VARCHAR(80),
UNIT_PRICE DECIMAL(10,2) NOT NULL CHECK (UNIT_PRICE >= 0),
REORDER_LEVEL INT NOT NULL DEFAULT 10 CHECK (REORDER_LEVEL >= 0),
SUPPLIER_ID INT NOT NULL,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_PRODUCT_SUPPLIER
FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 2.4 INVENTORY (STOCK OF EACH PRODUCT AT EACH WAREHOUSE) -----------------
CREATE TABLE INVENTORY (
INVENTORY_ID SERIAL PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
WAREHOUSE_ID INT NOT NULL,
QUANTITY_ON_HAND INT NOT NULL DEFAULT 0 CHECK (QUANTITY_ON_HAND >= 0),
LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT FK_INV_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
CONSTRAINT FK_INV_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID) ON DELETE CASCADE,
CONSTRAINT UQ_PRODUCT_WAREHOUSE UNIQUE (PRODUCT_ID, WAREHOUSE_ID)  -- ONE ROW PER PRODUCT/WAREHOUSE PAIR
);

-- 2.5 PURCHASE_ORDERS (RESTOCKING FROM SUPPLIERS) --------------------------
CREATE TABLE PURCHASE_ORDERS (
PO_ID SERIAL PRIMARY KEY,
SUPPLIER_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
WAREHOUSE_ID INT NOT NULL,
ORDER_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
UNIT_COST DECIMAL(10,2) NOT NULL CHECK (UNIT_COST >= 0),
STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING','RECEIVED','CANCELLED')),
CONSTRAINT FK_PO_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
CONSTRAINT FK_PO_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CONSTRAINT FK_PO_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

-- 2.6 SALES -----------------------------------------------------------------
CREATE TABLE SALES (
SALE_ID SERIAL PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
WAREHOUSE_ID INT NOT NULL,
SALE_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
QUANTITY_SOLD INT NOT NULL CHECK (QUANTITY_SOLD > 0),
UNIT_PRICE DECIMAL(10,2) NOT NULL CHECK (UNIT_PRICE >= 0),
CONSTRAINT FK_SALE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CONSTRAINT FK_SALE_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

-- 2.7 STOCK_MOVEMENTS (AUDIT TRAIL: IN / OUT / TRANSFER) --------------------
CREATE TABLE STOCK_MOVEMENTS (
MOVEMENT_ID SERIAL PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
WAREHOUSE_ID INT NOT NULL,
MOVEMENT_TYPE VARCHAR(10) NOT NULL CHECK (MOVEMENT_TYPE IN ('IN','OUT','TRANSFER')),
QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
MOVEMENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
REFERENCE_TYPE VARCHAR(20),
REFERENCE_ID INT,
CONSTRAINT FK_MOV_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
CONSTRAINT FK_MOV_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);


--SECTION 3: INDEXING

CREATE INDEX IDX_PRODUCTS_SUPPLIER ON PRODUCTS(SUPPLIER_ID);
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY);
CREATE INDEX IDX_INVENTORY_PRODUCT ON INVENTORY(PRODUCT_ID);
CREATE INDEX IDX_INVENTORY_WAREHOUSE ON INVENTORY(WAREHOUSE_ID);
CREATE INDEX IDX_PO_PRODUCT ON PURCHASE_ORDERS(PRODUCT_ID);
CREATE INDEX IDX_PO_SUPPLIER ON PURCHASE_ORDERS(SUPPLIER_ID);
CREATE INDEX IDX_PO_ORDER_DATE ON PURCHASE_ORDERS(ORDER_DATE);
CREATE INDEX IDX_SALES_PRODUCT ON SALES(PRODUCT_ID);
CREATE INDEX IDX_SALES_WAREHOUSE ON SALES(WAREHOUSE_ID);
CREATE INDEX IDX_SALES_DATE ON SALES(SALE_DATE);
CREATE INDEX IDX_MOVEMENTS_PRODUCT ON STOCK_MOVEMENTS(PRODUCT_ID);
CREATE INDEX IDX_MOVEMENTS_DATE ON STOCK_MOVEMENTS(MOVEMENT_DATE);

-- SECTION 4: SAMPLE DATA

INSERT INTO SUPPLIERS (SUPPLIER_NAME,CONTACT_NAME,PHONE,EMAIL,ADDRESS) VALUES
('GLOBAL PARTS CO.','MEGHA','111-222-3333','MEGHA@GLOBALPARTS.COM','12 MARKET ST, DELHI'),
('NORTHWIND TRADERS','ASHIQ','222-333-4444','ASHIQ@NORTHWIND.COM','88 TRADE AVE, MUMBAI'),
('PRIME DISTRIBUTORS','RAYA','333-444-5555','RAYA@PRIMEDIST.COM','5 HARBOR RD, CHENNAI');


INSERT INTO WAREHOUSES (WAREHOUSE_NAME, LOCATION, CAPACITY) VALUES
('CENTRAL WAREHOUSE','DELHI',50000),
('WEST COAST HUB','MUMBAI',40000),
('MIDWEST DEPOT','CHENNAI',30000);

INSERT INTO PRODUCTS (PRODUCT_NAME,CATEGORY,UNIT_PRICE,REORDER_LEVEL,SUPPLIER_ID) VALUES
('WIRELESS MOUSE','ELECTRONICS', 15.99,30,1),
('MECHANICAL KEYBOARD','ELECTRONICS', 45.50,20,1),
('USB-C CABLE','ACCESSORIES',5.99,50,2),
('OFFICE CHAIR','FURNITURE',89.00,10,3),
('STANDING DESK','FURNITURE',199.00,5,3),
('LAPTOP STAND','ACCESSORIES',25.00,15,2);

INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, QUANTITY_ON_HAND) VALUES
(1,1,12),(1,2,8),
(2,1,5),(2,3,10),
(3,1,100),(3,2,40),
(4,2,3),(5,1,2),
(6,3,60);

INSERT INTO PURCHASE_ORDERS (SUPPLIER_ID, PRODUCT_ID, WAREHOUSE_ID, ORDER_DATE, QUANTITY, UNIT_COST, STATUS) VALUES
(1,1,1,'2026-05-01',50,10.00,'RECEIVED'),
(1,2,3,'2026-06-10',30,30.00,'RECEIVED'),
(2,3,1,'2026-07-01',200,3.50,'PENDING'),
(3,4,2,'2026-04-15',20,60.00,'RECEIVED');

INSERT INTO SALES (PRODUCT_ID, WAREHOUSE_ID, SALE_DATE, QUANTITY_SOLD, UNIT_PRICE) VALUES
(1,1,'2026-07-20',3,15.99),
(3,1,'2026-08-01',10,5.99),
(3,2,'2026-07-15',5,5.99),
(6,3,'2026-06-05',4,25.00);

INSERT INTO STOCK_MOVEMENTS (PRODUCT_ID, WAREHOUSE_ID, MOVEMENT_TYPE, QUANTITY, REFERENCE_TYPE, REFERENCE_ID) VALUES
(1,1,'IN',50,'PURCHASE_ORDER',1),
(1,1,'OUT',3,'SALE',1),
(3,1,'OUT',10,'SALE',2),
(4,2,'IN',20,'PURCHASE_ORDER',4);

--SELECT OLTP TABLES
SELECT * FROM Suppliers;
SELECT * FROM Warehouses;
SELECT * FROM Products;
SELECT * FROM Inventory;
SELECT * FROM Purchase_Orders;
SELECT * FROM Sales;
SELECT * FROM Stock_Movements;

-- SECTION 5: CRUD OPERATIONS 

-- CREATE: ADD A NEW SUPPLIER AND A NEW PRODUCT
INSERT INTO SUPPLIERS (SUPPLIER_NAME, CONTACT_NAME, PHONE, EMAIL, ADDRESS)
VALUES ('APEX SUPPLIES','ANCY','444-555-6666','ANCY@APEXSUPPLIES.COM','9 INDUSTRIAL WAY, TX');

INSERT INTO PRODUCTS (PRODUCT_NAME, CATEGORY, UNIT_PRICE, REORDER_LEVEL, SUPPLIER_ID)
VALUES ('HDMI CABLE', 'ACCESSORIES', 7.49, 40, 2);

-- READ: FETCH A PRODUCT WITH ITS SUPPLIER
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.UNIT_PRICE, S.SUPPLIER_NAME
FROM PRODUCTS P
JOIN SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID
WHERE P.PRODUCT_ID = 1;

-- UPDATE: CORRECT A PRODUCT'S PRICE AND REORDER LEVEL
UPDATE PRODUCTS
SET UNIT_PRICE = 17.99, REORDER_LEVEL = 25
WHERE PRODUCT_ID = 1;

-- UPDATE: ADJUST STOCK AFTER A STOCK TAKE
UPDATE INVENTORY
SET QUANTITY_ON_HAND = QUANTITY_ON_HAND - 2, LAST_UPDATED = CURRENT_TIMESTAMP
WHERE PRODUCT_ID = 1 AND WAREHOUSE_ID = 1;

-- DELETE: REMOVE A CANCELLED PURCHASE ORDER
DELETE FROM PURCHASE_ORDERS
WHERE STATUS = 'CANCELLED';


-- SECTION 6: AGGREGATIONS & FUNCTIONS

--TOTAL PRODUCTS PER CATEGORY
SELECT CATEGORY, COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY;

--TOTAL STOCK QUANTITY PER PRODUCT ACROSS ALL WAREHOUSES
SELECT PRODUCT_ID, SUM(QUANTITY_ON_HAND) AS TOTAL_STOCK
FROM INVENTORY
GROUP BY PRODUCT_ID;

--AVERAGE, MIN, MAX UNIT PRICE PER CATEGORY
SELECT CATEGORY,
AVG(UNIT_PRICE) AS AVG_PRICE,
MIN(UNIT_PRICE) AS MIN_PRICE,
MAX(UNIT_PRICE) AS MAX_PRICE
FROM PRODUCTS
GROUP BY CATEGORY;

--TOTAL SALES REVENUE PER PRODUCT, ONLY PRODUCTS WITH REVENUE > 50
SELECT PRODUCT_ID,
SUM(QUANTITY_SOLD * UNIT_PRICE) AS TOTAL_REVENUE
FROM SALES
GROUP BY PRODUCT_ID
HAVING SUM(QUANTITY_SOLD * UNIT_PRICE) > 50;

--NUMBER OF PURCHASE ORDERS AND TOTAL QUANTITY ORDERED PER SUPPLIER
SELECT SUPPLIER_ID,
COUNT(PO_ID) AS ORDER_COUNT,
SUM(QUANTITY) AS TOTAL_UNITS_ORDERED
FROM PURCHASE_ORDERS
GROUP BY SUPPLIER_ID;


-- SECTION 7: JOINS & RELATIONSHIPS

--INNER JOIN: PRODUCTS WITH THEIR SUPPLIER NAME (ONLY MATCHED ROWS)
SELECT P.PRODUCT_NAME, S.SUPPLIER_NAME
FROM PRODUCTS P
INNER JOIN SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID;

--LEFT JOIN: ALL PRODUCTS, WITH INVENTORY IF IT EXISTS (PRODUCTS WITH NOTOCK ROW ANYWHERE STILL APPEAR, WITH NULLS)
SELECT P.PRODUCT_NAME, I.WAREHOUSE_ID, I.QUANTITY_ON_HAND
FROM PRODUCTS P
LEFT JOIN INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID;

--RIGHT JOIN: ALL WAREHOUSES, WITH INVENTORY IF IT EXISTS USING RIGHT JOIN )
SELECT W.WAREHOUSE_NAME, I.PRODUCT_ID, I.QUANTITY_ON_HAND
FROM INVENTORY I
RIGHT JOIN WAREHOUSES W ON I.WAREHOUSE_ID = W.WAREHOUSE_ID;

--FULL OUTER JOIN: EVERY PRODUCT AND EVERY SALE, MATCHED WHERE POSSIBLE
SELECT P.PRODUCT_NAME, S.SALE_ID, S.QUANTITY_SOLD
FROM PRODUCTS P
FULL OUTER JOIN SALES S ON P.PRODUCT_ID = S.PRODUCT_ID;

--MULTI-TABLE JOIN: FULL PICTURE OF A SALE (PRODUCT, WAREHOUSE, SUPPLIER)
SELECT S.SALE_ID, P.PRODUCT_NAME, W.WAREHOUSE_NAME, SUP.SUPPLIER_NAME,
S.QUANTITY_SOLD, S.UNIT_PRICE, (S.QUANTITY_SOLD * S.UNIT_PRICE) AS LINE_TOTAL
FROM SALES S JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN WAREHOUSES W ON S.WAREHOUSE_ID = W.WAREHOUSE_ID
JOIN SUPPLIERS SUP ON P.SUPPLIER_ID = SUP.SUPPLIER_ID;

-- SECTION 8: OLAP STAR SCHEMA (FACT_SALES + DIMENSIONS)

-- DIMENSION: PRODUCT (DENORMALIZED — INCLUDES CATEGORY & SUPPLIER NAME)
CREATE TABLE DIM_PRODUCT (
PRODUCT_KEY SERIAL PRIMARY KEY,
PRODUCT_ID INT NOT NULL,     
PRODUCT_NAME VARCHAR(150) NOT NULL,
CATEGORY VARCHAR(80),
SUPPLIER_NAME VARCHAR(150)
);

-- DIMENSION: WAREHOUSE
CREATE TABLE DIM_WAREHOUSE (
WAREHOUSE_KEY SERIAL PRIMARY KEY,
WAREHOUSE_ID INT NOT NULL,
WAREHOUSE_NAME VARCHAR(100) NOT NULL,
LOCATION VARCHAR(150)
);

-- DIMENSION: SUPPLIER
CREATE TABLE DIM_SUPPLIER (
SUPPLIER_KEY SERIAL PRIMARY KEY,
SUPPLIER_ID INT NOT NULL,
SUPPLIER_NAME VARCHAR(150) NOT NULL
);

-- DIMENSION: DATE 
CREATE TABLE DIM_DATE (
DATE_KEY INT PRIMARY KEY,
FULL_DATE DATE NOT NULL,
DAY INT,
MONTH INT,
QUARTER INT,
YEAR INT
);

-- FACT TABLE: ONE ROW PER SALE LINE, ONLY KEYS + ADDITIVE MEASURES
CREATE TABLE FACT_SALES (
SALE_KEY SERIAL PRIMARY KEY,
PRODUCT_KEY INT NOT NULL REFERENCES DIM_PRODUCT(PRODUCT_KEY),
WAREHOUSE_KEY INT NOT NULL REFERENCES DIM_WAREHOUSE(WAREHOUSE_KEY),
DATE_KEY INT NOT NULL REFERENCES DIM_DATE(DATE_KEY),
QUANTITY_SOLD INT NOT NULL,
UNIT_PRICE DECIMAL(10,2) NOT NULL,
TOTAL_REVENUE DECIMAL(12,2) NOT NULL
);

CREATE INDEX IDX_FACT_SALES_PRODUCT   ON FACT_SALES(PRODUCT_KEY);
CREATE INDEX IDX_FACT_SALES_WAREHOUSE ON FACT_SALES(WAREHOUSE_KEY);
CREATE INDEX IDX_FACT_SALES_DATE      ON FACT_SALES(DATE_KEY);

-- EXAMPLE ETL: POPULATE DIMENSIONS FROM THE OLTP TABLES
INSERT INTO DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, CATEGORY, SUPPLIER_NAME)
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY, S.SUPPLIER_NAME
FROM PRODUCTS P JOIN SUPPLIERS S ON P.SUPPLIER_ID = S.SUPPLIER_ID;

INSERT INTO DIM_WAREHOUSE (WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION)
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, LOCATION FROM WAREHOUSES;

INSERT INTO DIM_SUPPLIER (SUPPLIER_ID, SUPPLIER_NAME)
SELECT SUPPLIER_ID, SUPPLIER_NAME FROM SUPPLIERS;

-- EXAMPLE STAR-SCHEMA QUERY: TOTAL REVENUE BY MONTH AND CATEGORY
SELECT D.YEAR, D.MONTH, DP.CATEGORY, SUM(F.TOTAL_REVENUE) AS MONTHLY_REVENUE
FROM FACT_SALES F
JOIN DIM_DATE D ON F.DATE_KEY = D.DATE_KEY
JOIN DIM_PRODUCT DP ON F.PRODUCT_KEY = DP.PRODUCT_KEY
GROUP BY D.YEAR, D.MONTH, DP.CATEGORY
ORDER BY D.YEAR, D.MONTH;

-- SELECT FROM OLAP STAR SCHEMA TABLES
SELECT * FROM Dim_Product;
SELECT * FROM Dim_Warehouse;
SELECT * FROM Dim_Supplier;
SELECT * FROM Dim_Date;
SELECT * FROM Fact_Sales;

-- SECTION 9 : REAL-TIME QUERIES

-- LIST PRODUCTS WITH STOCK BELOW THE REORDER LEVEL
SELECT P.PRODUCT_ID,
P.PRODUCT_NAME,
COALESCE(SUM(I.QUANTITY_ON_HAND), 0) AS TOTAL_STOCK,
P.REORDER_LEVEL
FROM PRODUCTS P
LEFT JOIN INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.REORDER_LEVEL
HAVING COALESCE(SUM(I.QUANTITY_ON_HAND), 0) < P.REORDER_LEVEL
ORDER BY TOTAL_STOCK ASC;

-- FIND SUPPLIERS PROVIDING MORE THAN 20 PRODUCTS
SELECT S.SUPPLIER_ID,
S.SUPPLIER_NAME,
COUNT(P.PRODUCT_ID) AS PRODUCT_COUNT
FROM SUPPLIERS S
JOIN PRODUCTS P ON S.SUPPLIER_ID = P.SUPPLIER_ID
GROUP BY S.SUPPLIER_ID, S.SUPPLIER_NAME
HAVING COUNT(P.PRODUCT_ID) > 20;

-- CALCULATE WAREHOUSE-WISE INVENTORY VALUE (QTY * UNIT_PRICE)
SELECT W.WAREHOUSE_ID,
W.WAREHOUSE_NAME,
SUM(I.QUANTITY_ON_HAND * P.UNIT_PRICE) AS INVENTORY_VALUE
FROM WAREHOUSES W
JOIN INVENTORY I ON W.WAREHOUSE_ID = I.WAREHOUSE_ID
JOIN PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID
GROUP BY W.WAREHOUSE_ID, W.WAREHOUSE_NAME
ORDER BY INVENTORY_VALUE DESC;

--DISPLAY PRODUCTS THAT HAVEN'T BEEN SOLD IN THE LAST 6 MONTHS
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.CATEGORY
FROM PRODUCTS P
WHERE NOT EXISTS (
SELECT 1 FROM SALES S WHERE S.PRODUCT_ID = P.PRODUCT_ID
AND S.SALE_DATE >= CURRENT_DATE - INTERVAL '6 MONTHS')
ORDER BY P.PRODUCT_NAME;


--DROP TABLES
DROP TABLE IF EXISTS STOCK_MOVEMENTS CASCADE;
DROP TABLE IF EXISTS SALES CASCADE;
DROP TABLE IF EXISTS PURCHASE_ORDERS CASCADE;
DROP TABLE IF EXISTS INVENTORY CASCADE;
DROP TABLE IF EXISTS PRODUCTS CASCADE;
DROP TABLE IF EXISTS WAREHOUSES CASCADE;
DROP TABLE IF EXISTS SUPPLIERS CASCADE;
DROP TABLE IF EXISTS FACT_SALES CASCADE;
DROP TABLE IF EXISTS DIM_PRODUCT CASCADE;
DROP TABLE IF EXISTS DIM_WAREHOUSE CASCADE;
DROP TABLE IF EXISTS DIM_SUPPLIER CASCADE;
DROP TABLE IF EXISTS DIM_DATE CASCADE;