--CREATE TABLE
CREATE TABLE sales (sale_id SERIAL PRIMARY KEY,customer_name VARCHAR(50),
city VARCHAR(30),product VARCHAR(40),category VARCHAR(30),quantity INT,
price NUMERIC(10,2),sale_date DATE);

--INSERT INTO TABLE
INSERT INTO sales (customer_name, city, product, category, quantity, price, sale_date)
VALUES ('Alice','Chennai','Laptop','Electronics',2,55000,'2025-01-10'),
('Bob','Delhi','Mouse','Accessories',5,700,'2025-01-12'),
('Charlie','Mumbai','Laptop','Electronics',1,60000,'2025-01-15'),
('David','Delhi','Keyboard','Accessories',4,1200,'2025-01-18'),
('Eva','Chennai','Chair','Furniture',2,4500,'2025-01-20'),
('Frank','Bangalore','Desk','Furniture',1,9000,'2025-01-22'),
('Grace','Mumbai','Laptop','Electronics',3,65000,'2025-01-25'),
('Helen','Delhi','Chair','Furniture',5,5000,'2025-02-01'),
('Ian','Bangalore','Mouse','Accessories',8,650,'2025-02-03'),
('Jack','Chennai','Desk','Furniture',2,9500,'2025-02-05'),
('Kevin','Delhi','Laptop','Electronics',1,70000,'2025-02-08'),
('Lily','Mumbai','Keyboard','Accessories',7,1000,'2025-02-12'),
('Mary','Delhi','Chair','Furniture',2,5200,'2025-02-15'),
('Nancy','Chennai','Laptop','Electronics',1,62000,'2025-02-18'),
('Oscar','Bangalore','Desk','Furniture',3,9100,'2025-02-20');

--SELECT TABLE : SALES
SELECT * FROM SALES;

--COUNT()--------------------------------------------------------------------------------------------------------------------------------------
--COUNT TOTAL SALES
SELECT COUNT(*) FROM SALES;

--COUNT CUSTOMERS FORM DELHI
SELECT COUNT(DISTINCT customer_name) FROM SALES WHERE CITY='Delhi';

--Count Electronics Product
SELECT COUNT(product) FROM SALES WHERE category='Electronics';

--Count quantity >3
SELECT COUNT(*) FROM SALES WHERE QUANTITY>3;

--FUNCTION--------------------------------------------------------------------------------------------------------------------------------------
--DEFINE A FUNC FOR MULTIPLICATION
CREATE OR REPLACE FUNCTION MULTIPLY_NUMBERS(price NUMERIC,quantity INT)
RETURNS NUMERIC AS
$$
BEGIN
	RETURN quantity * price;
END;
$$
LANGUAGE plpgsql;

--SUM()--------------------------------------------------------------------------------------------------------------------------------------
--TOTAL REVENUE
SELECT SUM(MULTIPLY_NUMBERS(PRICE,QUANTITY)) AS TOTAL_REVENUE FROM SALES ;

--TOATAL FURNITURE SALE
SELECT COUNT(category) from sales WHERE category='Furniture';

--TOTAL QUANTITY SOLD
SELECT SUM(QUANTITY) AS TOTAL_SALES_QUANTITY FROM SALES;

--MIN()--------------------------------------------------------------------------------------------------------------------------------------
--FIND MIN PRICE
SELECT MIN(PRICE) FROM SALES;

--SMALLEST QUANTITY SOLD
SELECT MIN(QUANTITY) FROM SALES;

--EARLIEST SALE DATE
SELECT MIN(SALE_DATE) FROM SALES;

--MAX()--------------------------------------------------------------------------------------------------------------------------------------
--RECENT SALE DATE
SELECT MAX(SALE_DATE) FROM SALES;

--FIND MAX PRICE
SELECT MAX(PRICE) FROM SALES;

--MAX QUANTITY SOLD 
SELECT MAX(QUANTITY) FROM SALES;

--AVG()--------------------------------------------------------------------------------------------------------------------------------------
--AVERAGE OF PRICE
SELECT AVG(PRICE) FROM SALES;

--AVERAGE QUANTITY SOLD
SELECT AVG(QUANTITY) FROM SALES;

--AVERAGE LAPTOP PRICE
SELECT AVG(PRICE) FROM SALES WHERE PRODUCT='Laptop';

--DISTINCT--------------------------------------------------------------------------------------------------------------------------------------
--DISTINCT CITIES
SELECT DISTINCT(CITY) FROM SALES;

--UNIQUE CATEGORIES
SELECT DISTINCT(CATEGORY) FROM SALES;

--COUNT DISTINCT CITIES
SELECT COUNT(DISTINCT CITY) FROM SALES;

--COUNT DISTINCT PRODUCTS
SELECT COUNT(DISTINCT PRODUCT) FROM SALES;

--GROUP BY--------------------------------------------------------------------------------------------------------------------------------------
--SALE IN EACH CITY
SELECT CITY,COUNT(*) FROM SALES GROUP BY CITY;

--QUANTITY SOLD PER CATEGORY
SELECT CATEGORY,SUM(QUANTITY) FROM SALES GROUP BY CATEGORY;

--AVERAGE PRICE PER CATEGORY
SELECT CATEGORY, AVG(PRICE) FROM SALES GROUP BY CATEGORY;

--MAX PRICE FOR EACH PRODUCT
SELECT PRODUCT,MAX(PRICE) FROM SALES GROUP BY PRODUCT;

--MINIMUM QUANTITY FOR EACH CITY
SELECT CITY,MIN(QUANTITY) FROM SALES GROUP BY CITY;

--ORDER BY--------------------------------------------------------------------------------------------------------------------------------------
--TOTAL REVENUE PER CATEGORY ORDERED FROM GIGHEST REVENUE
SELECT CATEGORY,SUM(MULTIPLY_NUMBERS(PRICE,QUANTITY)) AS REVENUE FROM SALES GROUP BY CATEGORY ORDER BY REVENUE DESC;

--AVERAGE QUANTITY BY CITY IN DESCENDING ORDER
SELECT CITY,AVG(QUANTITY) AS AVG_QUANTITY FROM SALES GROUP BY CITY ORDER BY AVG_QUANTITY;

--COUNT OF PRODUCT SOLD ORDERED ALPHABETICALLY
SELECT PRODUCT,SUM(QUANTITY) AS SOLD FROM SALES GROUP BY PRODUCT ORDER BY PRODUCT;

--WHERE VS HAVING --------------------------------------------------------------------------------------------------------------------------------------
--AVERAGE PRICE OF ELECTRONICS ONLY - WHERE
SELECT AVG(PRICE) AS AVG_ELECTRONICS_PRICE FROM SALES WHERE CATEGORY='Electronics';

--CITIES WHOES QUANTITY EXCEED 10
SELECT CITY,SUM(QUANTITY) AS TOTAL_QUANTITY FROM SALES GROUP BY CITY HAVING SUM(QUANTITY)>10;

--CATEGORIES WHOES AVERAGE PRICE EXCEEDS 10000
SELECT CATEGORY,AVG(PRICE) AS AVERAGE FROM SALES GROUP BY CATEGORY HAVING AVG(PRICE)>10000;

--PRODUCTS HAVING MORE THAN 2 SALES
SELECT PRODUCT,COUNT(PRODUCT) FROM SALES GROUP BY PRODUCT HAVING COUNT(PRODUCT)>2;

--HAVING WITHOUT GROUP BY--------------------------------------------------------------------------------------------------------------------------------------
--TOTAL SALE ONLY IF TOTAL REVENUE EXCEEDS 500000
SELECT SUM(MULTIPLY_NUMBERS(PRICE,QUANTITY)) FROM SALES HAVING SUM(MULTIPLY_NUMBERS(PRICE,QUANTITY))>500000;

--AVERAGE PRICE ONLY IF AVERAGE PRICE EXCEEDS 10000
SELECT AVG(PRICE) FROM SALES HAVING AVG(PRICE)>10000;

--TOTAL QUANTITY IF TOTAL QUANTITY EXCEEDS 40
SELECT SUM(QUANTITY) FROM SALES HAVING SUM(QUANTITY)>40;

--FILTER CLAUSE--------------------------------------------------------------------------------------------------------------------------------------
--TOTAL ELECTRONICS REVENUE
SELECT SUM(MULTIPLY_NUMBERS(PRICE,QUANTITY)) FILTER (WHERE CATEGORY='Electronics') AS ELECTRONIC_REVENUE FROM SALES ;

--COUNT FURNITURE ORDERS
SELECT COUNT(PRODUCT) FILTER (WHERE CATEGORY='Furniture') FROM SALES;

--AVERAGE LAPTOP PRICE
SELECT AVG(PRICE) FILTER (WHERE PRODUCT='Laptop') FROM SALES;

--SUM OF QUANTITY FOR ELECTRONICS AND FURNITURE
SELECT CATEGORY,SUM(QUANTITY) FROM SALES WHERE CATEGORY IN ('Electronics','Furniture') GROUP BY CATEGORY ; 

--COUNT OF DELHI CUSTOMERS AND CHENNAI CUSTOMERS
SELECT CITY,COUNT(CUSTOMER_NAME) FROM SALES WHERE CITY IN ('Chennai','Delhi') GROUP BY CITY;

--STRING_AGG()--------------------------------------------------------------------------------------------------------------------------------------
--LIST ALL CUSTOMER NAME SEPERATED BY COMMAS
SELECT STRING_AGG(CUSTOMER_NAME,',') AS CUSTOMERS FROM SALES; 

--LIST ALL PRODUCT IN EACH CATEGORY
SELECT CATEGORY,STRING_AGG(PRODUCT,',') FROM SALES GROUP BY CATEGORY;

--CITIES ALPHABETICALLY SEPERATED BY |
SELECT STRING_AGG(DISTINCT CITY,'|') AS CITIES FROM SALES ;

--LIST DISTINCT PRODUCT
SELECT STRING_AGG(DISTINCT PRODUCT,'|') AS PRODUCTS FROM SALES

--STATISTICAL AGGREGATES()--------------------------------------------------------------------------------------------------------------------------------------
--POPULATED STDDEV OF PRICE
SELECT STDDEV_POP(PRICE) FROM SALES;

--SAMPLE STDDEV
SELECT STDDEV_SAMP(PRICE) FROM SALES;

--VARIANCE OF QUANTITY
SELECT VARIANCE(QUANTITY) FROM SALES;

--CORRELATION BETWEEN QUANTITY AND PRICE
SELECT CORR(PRICE,QUANTITY) FROM SALES;

--25TH PERCENTILE
SELECT PERCENTILE_CONT(0.25) WITHIN GROUP ( ORDER BY PRICE) FROM SALES;

--MEADIAN QUANTITY SOLD
SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY QUANTITY ) FROM SALES;

--75TH PERCENTILE OF PRICES
SELECT PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER  BY PRICE) FROM SALES;

 --90TH PERCENTILE OF PRICES
SELECT PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER  BY PRICE) FROM SALES;

--MEDIAN PRICE PER CATEGORY
SELECT CATEGORY,PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY PRICE) FROM SALES GROUP BY CATEGORY;

--MODE()--------------------------------------------------------------------------------------------------------------------------------------
--MODE OF QUANTIITY
SELECT MODE() WITHIN GROUP(ORDER BY QUANTITY) AS FREQ_QUANTITY FROM SALES;

--MODE OF PRICE
SELECT MODE() WITHIN GROUP(ORDER BY PRICE) AS FREQ_PRICE FROM SALES;

--MODE OF CATEGORY 
SELECT MODE() WITHIN GROUP(ORDER BY CATEGORY) AS FREQ_CATEGORY FROM SALES;

--WINDOW FUNCTIOM------------------------------------------------------------------------------------------------------------------------------
--SHOW EVERY ROW WITH TOTAL SALES ACROSS ALL ROWS
SELECT CUSTOMER_NAME, PRICE*QUANTITY AS REVENUE, SUM(PRICE*QUANTITY) OVER() AS TOTAL_REVENUE FROM SALES;

--EACH SALE WITH AVERAGE PRICE FOR ITS CITY
SELECT CUSTOMER_NMAE,CITY,QUANTITY,SUM(QUANTITY) OVER(PARTITION BY CITY) AS CITY_TOTAL_QUANTITY FROM SALES;

--ASSIGN ROW NUMBER WITHON EACH CITY 
SELECT CITY,CUSTOMER_NAME,ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY SALE_DATE) AS ROW_NO FROM SALES;

--RANK BY PRICE
SELECT PRODUCT,PRICE,RANK() OVER(ORDER BY PRICE DESC) AS RANK FROM SALES;

--PRODUCT WITH CATEGORY
SELECT CATEGORY,PRODUCT,PRICE,RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANK FROM SALES;

--DENSE RANK PRODUCT WITHIN CATEGORY
SELECT  CATEGORY,PRODUCT,PRICE,DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS DENSE_RANK FROM SALES;


---------------------------------------------- CHALLENGES -------------------------------------------------------------------------------------
--CITY NAME WITH HIGHEST TOTAL REVENUE
SELECT CITY,SUM(PRICE*QUANTITY) AS REVENUE FROM SALES GROUP BY CITY ORDER BY REVENUE DESC LIMIT 1;

--CATEGORY WITH HIGHEST AVERAGE PRICE
SELECT CATEGORY,AVG(PRICE) AS AVG_PRICE FROM SALES GROUP BY CATEGORY ORDER BY AVG_PRICE DESC LIMIT 1;

--Display categories where Total quantity > 5, Average price > 1000, Ordered by revenue descending
SELECT CATEGORY,SUM(QUANTITY),AVG(PRICE) AS AVG_PRICE, SUM(PRICE*QUANTITY) AS REVENUE FROM SALES GROUP BY CATEGORY HAVING SUM(QUANTITY)>5 AND AVG(PRICE)>1000 ORDER BY REVENUE DESC;
 






